### PR TITLE
add relative bearing calculation and test

### PR DESCRIPTION
**Pull request by foohines**

### CODE REVIEW

**Review by kthedude — CHANGES_REQUESTED** [review]
Add some comments on what the function takes in, what it returns, and what it does. Make sure to state that a positive result means turn right and a negative result means turn left

**Comment by foohines** [comment]
@kthedude So to be honest I'm not a fan of that style of commenting, nor have I ever come across it in industry. In my opinion code should be verbose and descriptive enough to be self-documenting -
 leaving no need for comments. 

The function name `getRelativeBearing` with the return of `float` seems descriptive enough to relay what it's doing and the parameter names are self explanatory within the context.

That being said, in this particular case, I think leaving a comment explaining the range of the output is beneficial, so I'll add that.

**Comment by foohines** [comment]
@kthedude So to be honest I'm not a fan of that style of commenting, nor have I ever come across it in industry. In my opinion code should be verbose and descriptive enough to be self-documenting -
 leaving no need for comments. 

The function name `getRelativeBearing` with the return of `float` seems descriptive enough to relay what it's doing and the parameter names are self explanatory within the context.

That being said, in this particular case, I think leaving a comment explaining the range of the output is beneficial, so I'll add that.

**Comment by kthedude** [comment]
@foohines I agree that the additional comments should not be needed, however, the other teams (driver and data filtering) will likely need more explicit comments to understand what is happening. In this case, I think explaining the output should be good enough.

**Review by kthedude — APPROVED** [review]

**Pull request merged**
